remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3

markdown: kramdown
kramdown:
  auto_ids: true
  toc_levels: 1..6

collections:
  pages:
    output: true
    permalink: /:collection/:path/